### ISSUE TITLE
gemspec: reference to include header directory 'include' is missing.

### ISSUE THREAD

**Issue by thisMagpie** [thisMagpie/fftw#19]
I reference the include folder headers in the gemspec because now I have cleared my header I am finding the gem does not compile unless I keep the header in ext and I don't want to do that but finding the correct command to use is not forthcoming at all! This question seems to need better googling skills than I have or perhaps my design to use include should be using a more ruby friendly directory structure, I don't know.

As far as I know it's an acceptable convention in ruby to keep headers in 'include' so I am keen to follow trend by doing that which means I don't want to put my headers in ext I want to have them in include but I cannot find a working example of how to implement that irreverence to the folder 'include' best, in a gem spec which means my code breaks unless I move the file to ext/fftw instead. Very tiresome! 

Can anyone give me a pointer on where I might solve this problem once and for future reference I'd like to know if there is a simple way to query the API to get answers like that which I should know about, if one exists!

@cjfuller, any ideas?

**Comment by cjfuller** [comment]
I'm not an expert in hacking the `extconf.rb` file to do what you want, but here's a (bit old) blog post on setting up header search paths.  I presume you could do something similar with relative rather than absolute paths?

http://tenderlovemaking.com/2010/12/11/writing-ruby-c-extensions-part-2.html

**Comment by thisMagpie** [comment]
@cjfuller I can find the headers but it's no use unless I can find the library, which I cannot find using the standard commands.

Accordingly, would you mind taking another look at extconf and see if you can spot why find_library is not seeking out mmatrix because there is not a lot I can do without that working so I have a ton of debug messages in there now. :-) 

It's weird. What seems to be going wrong is that it seems to look for the rc3 repo when it should look for the rc4 and the rc4 doesn't seem to generate the libraries properly for some reason which could actually be an nmatrix bug but I am not sure but in anycase I think perhaps the reason they are not found is because .so is not there. Only the .o gets generated by rc4.

Going to ping @mohawkjohn (and hopefully spell it right this time!) to see if he has an idea.

**Comment by cjfuller** [comment]
I imagine you've already looked at it, but my only thing to go off of is the extconf section starting at sciruby/rb-gsl/ext/extconf.rb:264.  I am worried that this may be a setup-specific problem.

Have you tried my previous suggestion of _not_ using the nmatrix C interface, and instead going through `rb_funcall`?  All that is required there is for you to do 'require nmatrix' somwhere in your ruby code, which should work smoothly via rubygems.  That will hopefully help you get other things worked out first, and then you can go back and optimize if that is rate-limiting.

I honestly think for cases that take any significant amount of time to do the FFT, the extra overhead of copying the data via the ruby interpreter, rather than via pure C, will be negligible.  In any case, it's worth doing the simpler implementation first, and then actually profiling the code to see what's rate-limiting rather than going through a bunch of headache to optimize this when it might not be necessary.

So if you had a function in C that has a `VALUE` containing a 2-D NMatrix, dtype float64, as an argument called `n`, this would look something like:

``` C
VALUE fft_my_nmatrix(VALUE n) {
  // 0, 0th element
  double x  = NUM2DBL(rb_funcall(n, rb_intern("[]"), 2, 0, 0));
  // etc.
```

Then put x into your FFTW data structure and loop over all elements.

(Additionally, a thought for @mohawkjohn: developing C libraries for use with NMatrix would potentially be significantly easier if we defined on NMatrix a developer-targeted ruby API method that returns the actual memory address of an NMatrix's storage as a ruby integer.  This would allow reading of an NMatrix's internal storage from C without having to configure everything correctly for finding headers/libraries, which is frankly nontrivial given how awful writing extconf.rb files is.)

**Comment by thisMagpie** [comment]
Hi @cjfuller thanks for the response.

I know I am takin the long way round. I'm just trying to get my head around the memory allocation I gues and figure out why querying nmatrix librariess has been so problematic and I believe there is an nmatrix bug because when I query the nmatrix library from my bundled dependencies then, the nmatrix library should be found but it is not being found and when I install rc4 the .so files are not generated, but that might be a seperate issue to design but I don''t know if it's a good idea to ignore it at this stage since it's an integral library to the cause. Even once rc4 has been installed it does not generate an nmatrix.so which which is weird since I am getting it directly from git (see `fftw.gemspec`) so either way that library should be found and rc4 should be downloaded and used regardless of how nmatrix is implemented I think (feel free to correct if I am wrong there though) 

Anyway, I am not averse the the suggestion, the only problem I have with it is that discussion on multidimentional dynamic array allocation seems to infer that free and alloc functions are going to be required and a class constructure overridden, which is why I was putting them in and trying to do the thing more in c++ than C where I can now. Well that and I was not sure what you meant and how that could work in the extension through lack of working examples of other gems which have done it (unless I am missing something obvious in gsl or somewhere?)

RE: NMatrix your example above, honestly, I had not understood you :) before and now have some questions about your example. I will look those functions in the API now though :-) but off hand:
-  How is that code snippit related to nmatrix?
- Could that not be any object at all?
-  If so, why call it an nmatrix function at all?
- Do I even need to find these nmatrix libraries or is requiring nmatrix going to be enough with this strategy?

Would you mind taking a look at my update to ext before you respond just in case it might be handy to have current context!

**Comment by thisMagpie** [comment]
Just to emphasise regarding the extconf discussion so it doesn't divert the core discussion of how to design the nmatrix stuff. To clarify:
-  I believe my extconf code is fine
-  I belive the problem is an nmatrix bug which means  nmatrix.0.1.0.rc4 does not generate it's .so file properly
- If anything is wrong in the code for nmatrix matters it would be wrong in my gemspec request itself.

I am going to change my git branch to nmatrix master and see if that brings any joy!

**Comment by translunar** [comment]
There is currently a problem with the NMatrix C API which is preventing it from working properly with gsl-nmatrix. @cjfuller can point you to the open issue. I do not have a solution yet.

I would suggest you follow @cjfuller's approach regardless, as it's much simpler and less prone to being deprecated by API changes.

**Comment by thisMagpie** [comment]
@mohawkjohn as I said, I have no problem with the idea in principle but I do need to understand what I am doing, myself first. 

In any case this gsl bug cannot be connected since the gsl gem is using 0.0.9 not 0.1.0.rc4 or 0.1.0.rc3 even. Have you tried rb-gsl with a newer nmatrix version?

**Comment by translunar** [comment]
No, rb-gsl requires "> 0.0.9" for NMatrix:

https://github.com/SciRuby/rb-gsl/blob/master/gsl.gemspec#L21

And yes, of course, I've tried it with other versions.

**Comment by cjfuller** [comment]
I guess I'm unsure how nmatrix rc4 could not be generating its .so file in general because lots of people have used that version, and it would be entirely nonfunctional without it.  It's possible, though, that the location where it's being put is different (and this may be entirely unrelated to nmatrix).

The way you have it set up in the gemfile, it would put the .so file in whatever directory bundler has decided is where it's going to keep C extensions for your gems for this project (based on your particular configuration).  This is bundler's internal decision, and I suspect they could change it, so I wouldn't rely on a particular location from installing it this way.

In answer to your questions:
- How is that code snippit related to nmatrix? Could that not be any object at all?

I'm assuming that the `VALUE n` being passed in is an nmatrix.  It would work just fine based on that example alone with anything that responds to `[]`, though.  That's the beauty of duck typing!  Later on, though, when you're filling the output, you'd need to make a new NMatrix object, so there, you'd be using `rb_funcall` with more specific NMatrix methods.
- If so, why call it an nmatrix function at all?

The etc. portion will presumably return an NMatrix.
- Do I even need to find these nmatrix libraries or is requiring nmatrix going to be enough with this strategy?

Requiring nmatrix as a gem will be enough for this strategy, so you don't need to explicitly find the libraries or headers or do anything with nmatrix at all from C/C++ code or extconf (which is the main benefit of this strategy).

**Comment by thisMagpie** [comment]
No, @mohawkjohn currently the dependency to gemspec is being ignored by bundle.

See my pull request for gsl https://github.com/SciRuby/rb-gsl/pull/6 which fixes that.

**Comment by thisMagpie** [comment]
@cjfuller that makes a lot of sense in my book becase it would mean that other data types could be used and this would extend the flexibility of the gem to anyone whether they use nmatrix or not, which would make it more widely useful, I imagine.

I am going to try out what yo suggest. In any case I think I should file a bug against nmatrix though but I will download a fresh rc4 to check my theory is correct, given your skepticism about it. Do you remember at the start of GSoC when you showd me how to fix that problem in my own nmatrix install though? There's no smoke without fire :-)

**Comment by thisMagpie** [comment]
@mohawkjohn fyi I fixed the syntax in the gsl.gemspec, as now it is called from Gemfile it actually breaks the build. I am not sure what version you would normally prefer but `> 0.9.0` is not allowed so I just made a guess at `~>0.1.0.rc3` since that syntax worked and fixed this bug.
