### ISSUE TITLE
cast error calling rb_define_*

### ISSUE THREAD

**Issue by thisMagpie** [thisMagpie/fftw#22]
I am having a lot of trouble figuring out why my `rb_define_singleton_method` or `rb_define_method` calls are breaking when I run the command rake compile which sees the build fails with the following error when `extconf` calls `make`

The error means I am not able to test the functions in ruby at all because I need to make this definition successful, first so I have stripped the file to the minimum to try and do that

So far I have tried casting with a variety of types, none of which seemed to work. I am beginning to suspect I am setting things up wrong in extconf with my flags and compiler choice, but I am still nonethewiser

@cjfuller any ideas/suggestions on this?

**Comment by cjfuller** [comment]
I think the issue is that `rb_define_singleton_method`'s third argument needs to be a function pointer with a variable number of arguments, and you're feeding it a function of exactly two args.  This isn't a problem except that you need to cast the function to (in an incredibly confusing bit of C cyntax...) `VALUE (*)(...)`.  So that line in fftw.cpp would read:

``` C
rb_define_singleton_method(cNMatrix, "r2c", (VALUE (*)(...)) fftw_r2c, 2);
```

(That's also actually just three dots in there, not just me leaving stuff out with an ellipsis.)

In NMatrix, we've made that a typedef called `METHOD` so it looks less confusing.  See `nmatrix.h:354`.

**Comment by thisMagpie** [comment]
YEASSSSSSSSSSSSS!

**Comment by thisMagpie** [comment]
@cjfuller one quick question actually:

Does the last argument represent the number of arguments in the method itself?

**Comment by cjfuller** [comment]
Yes, I think that's correct.  There's also some special behavior if you set it to -1 that allows you to pass a variable number of arguments.  I don't remember the particulars of that, though.

**Comment by thisMagpie** [comment]
is -1 not void or null?

**Comment by thisMagpie** [comment]
ah no apparently it's this!: https://github.com/ruby/ruby/blob/trunk/README.EXT#L348
